# -*- coding: utf-8 -*-
"""
This plugin is generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
This script initializes the plugin, making it known to QGIS.
"""
import sys
sys.dont_write_bytecode = True

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load aggregate_inside_buffer class from file aggregate_inside_buffer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    import sys
    sys.dont_write_bytecode = True
    from .aggregate_inside_buffer import aggregate_inside_buffer
    return aggregate_inside_buffer(iface)
